plazos = {
    "Hunty Pro Mensual O.": 1,  # 1 mes
    "Hunty Pro Trimestral O.": 3,  # 3 meses
    "Hunty Pro Semestral O.": 6,  # 6 meses
    "Hunty Pro Mensual HF.": 1,
    "Hunty Pro Trimestral HF.": 3,
    "Hunty Pro Semestral HF.": 6,
    "Hunty Pro Mensual UT.": 1,
    "Hunty Pro Trimestral UT.": 3,
    "Hunty Pro Semestral UT.": 6,
    "Hunty Pro Mensual UP.": 1,
    "Hunty Pro Trimestral UP.": 3,
    "Hunty Pro Semestral UP.": 6,
    "Hunty Pro Mensual D.": 1,
    "Hunty Pro Trimestral D.": 3,
    "Hunty Pro Semestral D.": 6,
    "Hunty Pro Mensual DB.": 1,
    "Hunty Pro Trimestral DB.": 3,
    "Hunty Pro Semestral DB.": 6,
    "Hunty Pro Mensual T.": 1,
    "Hunty Pro Trimestral T.": 3,
    "Hunty Pro Semestral T.": 6,
    "Hunty Pro Mensual TB.": 1,
    "Hunty Pro Trimestral TB.": 3,
    "Hunty Pro Semestral TB.": 6,
    "Hunty Pro Mensual C.": 1,
    "Hunty Pro Trimestral C.": 3,
    "Hunty Pro Semestral C.": 6,
    "Hunty Pro Mensual Q.": 1,
    "Hunty Pro Trimestral Q.": 3,
    "Hunty Pro Semestral Q.": 6,
    "Hunty Pro Mensual S.": 1,
    "Hunty Pro Trimestral S.": 3,
    "Hunty Pro Semestral S.": 6,
    "Outplacement Gold": 3,
}
